# Generated by Django 5.2.6 on 2025-09-07 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_public', models.BooleanField(default=False)),
                ('entreprise_proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_possedes', to='entreprise.entreprise')),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'unique_together': {('nom', 'entreprise_proprietaire')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('type_message', models.CharField(choices=[('GROUPE_PUBLIC', 'Message public du groupe'), ('GROUPE_PRIVE', 'Message privé du groupe (membres seulement)'), ('DIRECT', 'Message direct')], max_length=15)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('est_lu', models.BooleanField(default=False)),
                ('est_modifie', models.BooleanField(default=False)),
                ('date_modification', models.DateTimeField(blank=True, null=True)),
                ('destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to='entreprise.entreprise')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to='entreprise.entreprise')),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entreprise.groupe')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='ConversationDirecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_activite', models.DateTimeField(auto_now=True)),
                ('entreprise1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_1', to='entreprise.entreprise')),
                ('entreprise2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_2', to='entreprise.entreprise')),
            ],
            options={
                'verbose_name': 'Conversation directe',
                'verbose_name_plural': 'Conversations directes',
                'unique_together': {('entreprise1', 'entreprise2')},
            },
        ),
        migrations.CreateModel(
            name='DemandeIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_demande', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=15)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('entreprise_demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_envoyees', to='entreprise.entreprise')),
                ('reponse_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to='entreprise.entreprise')),
                ('groupe_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.groupe')),
            ],
            options={
                'verbose_name': "Demande d'intégration",
                'verbose_name_plural': "Demandes d'intégration",
                'unique_together': {('entreprise_demandeur', 'groupe_cible')},
            },
        ),
        migrations.CreateModel(
            name='MembreGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('PROPRIETAIRE', 'Propriétaire'), ('MEMBRE', 'Membre'), ('INVITE', 'Invité')], max_length=15)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres_ajoutes', to='entreprise.entreprise')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.groupe')),
            ],
            options={
                'verbose_name': 'Membre du groupe',
                'verbose_name_plural': 'Membres du groupe',
                'unique_together': {('entreprise', 'groupe')},
            },
        ),
    ]
